### ISSUE TITLE
Compilation errors with npm run dev

### ISSUE THREAD

**Issue by sagaio** [ais-one/vue-crud-x#16]
I'm getting Syntax error for the spread operator after installing and running `npm run dev`. After installing the "babel-plugin-transform-object-rest-spread" I'm now getting Unexpected token error for the import statements for the component imports.

What am I doing wrong?

**Comment by ais-one** [comment]
what version of nodeJS are you using?

**Comment by ais-one** [comment]
there is one more plugin you need to add for handling "import", please see my article 

https://codeburst.io/apollo-graphql-server-express-google-cloud-function-serverless-framework-dbb6b5cf4bb3

Search for the text...  Babel polyfill dependencies, for using import/export and async/await

It would be best if you used NodeJS 8 or better...

**Comment by ais-one** [comment]
closing due to no further comment
