### ISSUE TITLE
metadata from firestore

### ISSUE THREAD

**Issue by abeperl** [ais-one/vue-crud-x#44]
for me the "exists" is always false.

       const metaRef = firestore.collection('meta').doc('party')

        const meta = await t.get(metaRef)
        if (!meta.exists) {
          throw new Error(500)
        }

Thanks

**Comment by ais-one** [comment]
let me check...

**Comment by ais-one** [comment]
Issue has been fixed in the develop branch, please see link below for diff...

https://github.com/ais-one/vue-crud-x/commit/c32dd621abcea84ca3bbacc1ecb3e791646e5b67

Will merge to master once the example backend is  are done

**Comment by ais-one** [comment]
> Issue has been fixed in the develop branch, please see link below for diff...
> 
> [c32dd62](https://github.com/ais-one/vue-crud-x/commit/c32dd621abcea84ca3bbacc1ecb3e791646e5b67)
> 
> Will merge to master once the example backend is are done

Code will now create meta if it did not exist...

Thank you for catching this problem
