### ISSUE TITLE
backend install failure at windows op. system

### ISSUE THREAD

**Issue by drascom** [ais-one/vue-crud-x#49]
npm run init-db have error at windows op system because of line below at vue-crud-x >backend >package.json line 7
"init-db": "rm -f dev.sqlite3&&npx knex migrate:latest --env development&&npx knex seed:run --env development",

windows dont have "rm" windows users have to change it to "del".
better to mention this to the installation notes

**Comment by ais-one** [comment]
Hi you are correct. Unless you install Git and incorporate bash.

Let me see if I can make it work across environments... if not I will see if I can make a note.

**Comment by ais-one** [comment]
removed OS dependent code in v0.2.1
