### ISSUE TITLE
example-rest cannot be run : backend/models/user.js has wrong filename / VueCrudX cannot be loaded

### ISSUE THREAD

**Issue by bedinsky** [ais-one/vue-crud-x#65]
Hi, I've tried to run example-rest but I found some issues

There was a trivial one on backend project, because on your git repository ./models/User.js was committed as ./models/user.js. Backend runs after changing filename.

I was not able to fix issue on example-rest, it seems that VueCrudX cannot be loaded

bedinsky@CPR-DSK-10-313:~/git/vue-crud-x/example-rest$ npm run serve

> example-rest@0.0.0 serve /home/bedinsky/git/vue-crud-x/example-rest
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin                                                    

 ERROR  Failed to compile with 1 errors                                                                 15:56:33

This dependency was not found:

* core-js/modules/web.dom.iterable in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!../src/VueCrudX.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save core-js/modules/web.dom.iterable

**Comment by ais-one** [comment]
Hi,

The problem is I am developing in windows. I have seen the case-sensitivity issue occur.

Even if I change to the correct case on my local machine, when uploaded to git, it still shows wrong case.

Anyway, please ignore try again, I am uploading version 0.2.0, it is an improvement from 0.1.x, and uses the upcoming Vuetify 2.

I will attempt to fix the issues you reported on the v1 branch after this.

**Comment by ais-one** [comment]
For the non trivial issue, quick and dirty fix is to

Copy the VueCrudX.vue file from vue-crud-x/src into your example-rest/src, then reference it from there is your imports

**Comment by bedinsky** [comment]
Thank you ! I'll wait for 0.2.0
I suggest to fix case-sensitivity iusses with git command like:
git mv hello.txt Hello.txt

**Comment by ais-one** [comment]
Thanks, will fix it, I just pushed 0.2

Let me get it tested on a Mac tonight and test drive...
