### ISSUE TITLE
missing init-db script

### ISSUE THREAD

**Issue by gelmo81** [ais-one/vue-crud-x#68]
/vue-crud-x/example-spa
> cd ../backend&&npm run-script init-db

npm ERR! missing script: init-db

**Comment by ais-one** [comment]
ok let me check

**Comment by ais-one** [comment]
Hi change "init-db" to just "db" for now. I will fix this and push it in next release...

**Comment by ais-one** [comment]
fixed,

https://github.com/ais-one/vue-crud-x/pull/73
