### ISSUE TITLE
Small typo in backend/models/users.js file name 

### ISSUE THREAD

**Issue by acoveny** [ais-one/vue-crud-x#74]
Hi @ais-one thank-you very much for this component and the example.  

For the example-spa to work the file backend/models/user.js needed to be renamed to backend/models/User.js 

Apologies for not submitting the change myself.

**Comment by ais-one** [comment]
Hi,

Thanks for pointing this out. It had something to do with windows and case insensitivity I think...

I will fix this and roll out an update soon (there are some fixes to be done, the logic for infinite scroll did not work after upgrading to latest Vuetify...), also updating on the packages.

**Comment by ais-one** [comment]
fixed in https://github.com/ais-one/vue-crud-x/pull/75

**Comment by acoveny** [comment]
Hi Aaron,

Wow you are fast.

Would like to repeat thanks heaps for putting this together, looking to
forward to learning some more and playing some more :-)

Cheers,

Anne C

**Comment by ais-one** [comment]
No problem, let me know if there is any other improvement that can be made...
