### ISSUE TITLE
Make it PWA?

### ISSUE THREAD

**Issue by gabrieligbastos** [ais-one/vue-crud-x#80]

**Comment by ais-one** [comment]
Hi,

I have added it to the [wiki - item 6 (not in order of priority)](https://github.com/ais-one/vue-crud-x/wiki).

The PWA will be part of a cookbook and not affect the VueCrudX component itself.

I have a project using VueCrudX in a PWA.

There is one important thing to note is that if you want to handle Push Notifications (android only, IOS not ready yet AFAIK)...

You need to use custom service worker...

[This article](https://swina.github.io/2019/02/vue-service-worker-for-webpush-notifications/) helped alot.

**Comment by gabrieligbastos** [comment]
oh perfect, it makes sense for me now ;) thanks for quickly reply
